import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { APP_TITLE } from '@/lib/constants';
import { ThemeProvider } from '@/components/theme-provider';

const inter = Inter({
  // variable: '--font-geist-sans',
  subsets: ['latin'],
});

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

export const metadata: Metadata = {
  title: {
    template: `%s | ${APP_TITLE}`,
    default: `${APP_TITLE}`,
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          // enableSystem
          // disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
